import { Check, Expand, ExternalLink, Shrink } from "lucide-react";
import { useState } from "react";

import { cn } from "@/lib/utils";

import { Preview } from "./preview";
import { PreviewMode, PreviewToggle } from "./preview-toggle";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "./ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
} from "./ui/dialog";

type OptionCardProps = {
  src: string;
  option: "a" | "b";
  isSelected: boolean;
  voteSubmitted: boolean;
  previewMode: PreviewMode;
  model: string | null;
  onSelect: () => void;
  setPreviewMode: (value: PreviewMode) => void;
};

type OptionPreviewProps = {
  src: string;
  optionLabel: string;
  isSelected: boolean;
  voteSubmitted: boolean;
  previewMode: PreviewMode;
  model: string | null;
  onSelect: () => void;
  setPreviewMode: (value: PreviewMode) => void;
  maximised?: boolean;
  setIsMaximised: (value: boolean) => void;
};

export function OptionCard({
  src,
  option,
  isSelected,
  previewMode,
  voteSubmitted,
  model,
  onSelect,
  setPreviewMode,
}: OptionCardProps) {
  const [isMaximised, setIsMaximised] = useState(false);

  const optionLabel = `Option ${option.toUpperCase()}`;

  return (
    <>
      <div className="h-full w-full bg-transparent">
        <OptionPreview
          src={src}
          optionLabel={optionLabel}
          previewMode={previewMode}
          setPreviewMode={setPreviewMode}
          onSelect={onSelect}
          isSelected={isSelected}
          voteSubmitted={voteSubmitted}
          model={model}
          setIsMaximised={setIsMaximised}
        />
      </div>

      <Dialog open={isMaximised} onOpenChange={setIsMaximised}>
        <DialogContent className="top-0 left-0 h-screen w-screen max-w-none translate-x-0 translate-y-0 rounded-none border-0 p-0 sm:max-w-none [&>button]:hidden">
          <DialogTitle className="sr-only">
            {optionLabel} maximised preview
          </DialogTitle>
          <DialogDescription className="sr-only">
            Full-size preview for {optionLabel}
          </DialogDescription>

          <OptionPreview
            src={src}
            optionLabel={optionLabel}
            previewMode={previewMode}
            setPreviewMode={setPreviewMode}
            onSelect={onSelect}
            isSelected={isSelected}
            voteSubmitted={voteSubmitted}
            model={model}
            maximised
            setIsMaximised={setIsMaximised}
          />
        </DialogContent>
      </Dialog>
    </>
  );
}

function OptionPreview({
  src,
  optionLabel,
  isSelected,
  previewMode,
  voteSubmitted,
  model,
  onSelect,
  setPreviewMode,
  setIsMaximised,
  maximised = false,
}: OptionPreviewProps) {
  const getButtonLabel = () => {
    if (voteSubmitted && isSelected) return `Shipped ${optionLabel}`;
    if (voteSubmitted && !isSelected) return `Skipped ${optionLabel}`;
    return `Ship ${optionLabel}`;
  };

  return (
    <Card
      aria-selected={isSelected}
      onClick={() => {
        if (!voteSubmitted && !maximised) onSelect();
      }}
      className={cn(
        "flex h-full w-full flex-col gap-1 overflow-clip border shadow-none transition-[background-color,box-shadow,opacity] duration-300",
        maximised
          ? "rounded-none border-none px-16 py-12"
          : "group hover:bg-accent/70",
        !maximised && !voteSubmitted && "cursor-pointer",
        !maximised && isSelected && "ring-primary scale-101 ring-2",
        !maximised && !isSelected && "scale-99",
        !maximised && voteSubmitted && !isSelected && "opacity-70",
      )}
    >
      <CardHeader className="flex flex-row justify-between gap-4">
        <div className="space-y-1">
          <CardTitle className="flex items-start gap-2">
            {optionLabel}

            {voteSubmitted && isSelected && <Badge>Shipped</Badge>}

            {voteSubmitted && !isSelected && (
              <Badge variant="secondary">Skipped</Badge>
            )}
          </CardTitle>

          <p
            className={cn(
              "text-muted-foreground text-sm",
              voteSubmitted && model ? "visible" : "invisible",
            )}
          >
            Generated by{" "}
            <span className="text-foreground font-medium">
              {model ?? "Unknown"}
            </span>
          </p>
        </div>

        <OptionActions
          src={src}
          optionLabel={optionLabel}
          maximised={maximised}
          previewMode={previewMode}
          setPreviewMode={setPreviewMode}
          setIsMaximised={setIsMaximised}
        />
      </CardHeader>

      <CardContent
        className={cn(
          "relative flex flex-1 items-center overflow-hidden",
          !maximised && "aspect-video",
          maximised && "min-h-0",
        )}
      >
        <Preview
          src={src}
          title={optionLabel}
          previewMode={previewMode}
          isMaximised={maximised}
        />
      </CardContent>

      {!maximised && (
        <CardFooter className="mt-4 flex justify-center border-t p-0">
          <Button
            className="w-full rounded-t-none rounded-b-xl border-0 py-6"
            onClick={(event) => {
              event.stopPropagation();
              onSelect();
            }}
            aria-pressed={isSelected}
            size="lg"
            disabled={voteSubmitted}
          >
            {isSelected && <Check className="h-4 w-4" aria-hidden="true" />}
            {getButtonLabel()}
          </Button>
        </CardFooter>
      )}
    </Card>
  );
}

function OptionActions({
  src,
  optionLabel,
  maximised,
  previewMode,
  setPreviewMode,
  setIsMaximised,
}: {
  src: string;
  optionLabel: string;
  maximised: boolean;
  previewMode: PreviewMode;
  setPreviewMode: (value: PreviewMode) => void;
  setIsMaximised: (value: boolean) => void;
}) {
  return (
    <div className="flex gap-2">
      {maximised && (
        <PreviewToggle value={previewMode} onChange={setPreviewMode} />
      )}

      <Button
        size="icon"
        variant="ghost"
        onClick={(event) => {
          event.stopPropagation();
          setIsMaximised(!maximised);
        }}
        aria-label={maximised ? "Close maximised view" : "Open maximised view"}
      >
        {maximised ? (
          <Shrink className="h-4 w-4" />
        ) : (
          <Expand className="h-4 w-4" />
        )}
      </Button>

      <Button size="icon" variant="ghost" asChild>
        <a
          href={src}
          target="_blank"
          rel="noreferrer"
          aria-label={`Open ${optionLabel} preview in a new tab`}
          onClick={(event) => event.stopPropagation()}
        >
          <ExternalLink className="h-4 w-4" />
        </a>
      </Button>
    </div>
  );
}
