import { Check, ExternalLink } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { cn, getPreviewUrl } from "@/lib/utils";

import { Preview, type PreviewMode } from "./preview";

export function OptionCard({
  id,
  label,
  model,
  isSelected,
  voteSubmitted,
  mode,
  onSelect,
}: {
  id: string;
  label: string;
  model: string | null;
  isSelected: boolean;
  voteSubmitted: boolean;
  mode: PreviewMode;
  onSelect: () => void;
}) {
  const src = getPreviewUrl(id);
  return (
    <Card
      onClick={() => {
        if (!voteSubmitted) onSelect();
      }}
      className={cn(
        "flex h-full w-full flex-col gap-1 overflow-clip border shadow-none transition-all duration-300",
        !voteSubmitted && "hover:bg-accent/70 cursor-pointer",
        isSelected && "ring-primary scale-[1.01] ring-2",
        !isSelected && "scale-[0.99]",
        voteSubmitted && !isSelected && "opacity-70",
      )}
    >
      <CardHeader className="flex flex-row justify-between gap-4">
        <div className="space-y-1">
          <CardTitle className="flex items-start gap-2">
            {label}
            {voteSubmitted && isSelected && <Badge>Shipped</Badge>}
            {voteSubmitted && !isSelected && (
              <Badge variant="secondary">Skipped</Badge>
            )}
          </CardTitle>
          <p
            className={cn(
              "text-muted-foreground text-sm",
              voteSubmitted && model ? "visible" : "invisible",
            )}
          >
            Generated by{" "}
            <span className="text-foreground font-medium">
              {model ?? "Unknown"}
            </span>
          </p>
        </div>
        <a
          href={src}
          target="_blank"
          rel="noopener noreferrer"
          onClick={(e) => e.stopPropagation()}
          className="text-muted-foreground hover:text-foreground transition-colors"
          aria-label={`Open ${label} in new tab`}
        >
          <ExternalLink className="size-4" />
        </a>
      </CardHeader>

      <CardContent className="relative flex aspect-video flex-1 items-center overflow-hidden">
        <Preview src={src} title={label} mode={mode} />
      </CardContent>

      <CardFooter className="mt-4 flex justify-center border-t p-0">
        <Button
          type="button"
          className="w-full rounded-t-none rounded-b-xl border-0 py-6"
          onClick={(e) => {
            e.stopPropagation();
            onSelect();
          }}
          aria-pressed={isSelected}
          size="lg"
          disabled={voteSubmitted}
        >
          {isSelected && <Check className="h-4 w-4" aria-hidden="true" />}
          {voteSubmitted
            ? isSelected
              ? `Shipped ${label}`
              : `Skipped ${label}`
            : `Ship ${label}`}
        </Button>
      </CardFooter>
    </Card>
  );
}
